In [3]:
import numpy as np

a = np.random.randn(5)

In [6]:
print(a)
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

[ 1.46831107 -0.04526713  1.5372774  -0.14687877  0.06825003]
(5,)
[ 1.46831107 -0.04526713  1.5372774  -0.14687877  0.06825003]
4.547439752052777


In [8]:
## (5) 로 설정하면 전치가 안되니, (5,1)과 같이 쓰는게 좋다.
## rank 1 배열 사용을 지양하자.
a = np.random.randn(5,1)


In [9]:
print(a)
print(a.shape)
print(a.T)
print(np.dot(a,a.T))

[[-0.95577204]
 [ 0.6897166 ]
 [ 0.077668  ]
 [-0.21307174]
 [ 1.69372117]]
(5, 1)
[[-0.95577204  0.6897166   0.077668   -0.21307174  1.69372117]]
[[ 0.91350019 -0.65921184 -0.07423291  0.20364802 -1.61881134]
 [-0.65921184  0.47570899  0.05356891 -0.14695912  1.16818761]
 [-0.07423291  0.05356891  0.00603232 -0.01654886  0.13154794]
 [ 0.20364802 -0.14695912 -0.01654886  0.04539957 -0.36088412]
 [-1.61881134  1.16818761  0.13154794 -0.36088412  2.86869141]]
